#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running tests..."
npm test

if [ $? -ne 0 ]; then
  echo "Tests failed. Commit aborted."
  exit 1
fi

echo "Running ESLint..."
npm run lint

if [ $? -ne 0 ]; then
  echo "Linting failed. Commit aborted."
  exit 1
fi

echo "Running Prettier..."
npm run format

echo "Running lint-staged..."
npx lint-staged
